# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'my-wso2ei-integrator-650-test'

steps:
- script: echo Try to start!
  displayName: 'Run a one-line script'
- task: Docker@2
  displayName: Build an wso2 image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: dockerfiles/ubuntu/integrator/Dockerfile
    containerRegistry: wso2-container-registry


